### ISSUE TITLE
SketchyBar causes switching to be slower (when doing three-finger swipe on trackpad)

### ISSUE THREAD

**Issue by iCraft85** [FelixKratz/SketchyBar#393] opened 2023-09-02 09:25 UTC
So when I am running SketchyBar and I do the three-finger swipe so that I can switch to another desktop it seems to take atleast 3 - 4 seconds before it switches.

When I turn of SketchyBar it seems to happen instantaneously. When I switch desktops through other means when running SketchyBar there seems to be no slowdown, so I don't believe it's due to performance but I am not entirely sure what is causing it.

**Comment by FelixKratz** [comment] 2023-09-02 09:27
Duplicate of #220, turn off the sticky property or disable space change animations.

**Closed by FelixKratz** 2023-09-02 09:27 UTC
