### ISSUE TITLE
Hidden spaces reappear after switching spaces

### ISSUE THREAD

**Issue by jpcrs** [FelixKratz/SketchyBar#307] opened 2023-01-01 16:23 UTC
I am attempting to hide certain spaces on certain conditions using the `sketchybar --set $space drawing=off` command. 

This works when the bar loads (calling `space.sh` for every space because of `sketchybar --update`), but after switching to a new space, the previously hidden spaces reappear.

Here is an example of a simple scenario where it should only show the current selected space:

`sketchybarrc`
```
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13")
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space      space.$sid left                               \
             --set space.$sid associated_space=$sid                         \
                              icon=${SPACE_ICONS[i]}                        \
                              script="$PLUGIN_DIR/space.sh"
done

sketchybar --update
```

`space.sh`
```
if [ "$SELECTED" = "true" ]; then
  sketchybar --set $NAME drawing=on
else
  sketchybar --set $NAME drawing=off
fi
```

Expected  behaviour:
If I'm in the space 4, just the space `4` is draw in the bar, after I switch to the space `6`, the space `4` goes hidden and the space `6` is draw.

Current behaviour:
If I'm in the space 4, just the space `4` is draw in the bar, after I switch to the space `6`, the space `4` goes hidden and all the other spaces (`1235678910111213`) are draw.

**Comment by FelixKratz** [comment] 2023-01-01 16:40
The problem is here:
https://github.com/FelixKratz/SketchyBar/blob/4b3008f8dcce71676362bc0f177b9f2a7928c6ce/src/bar_manager.c#L450-L459

I am overriding `bar_item->drawing` on the space update event. I think I can remove this and then your expected behavior would work perfectly fine.

If you are only interested in drawing the current space there is another way to do it very elegantly like this: #289

**Comment by FelixKratz** [comment] 2023-01-02 00:21
It should be fixed on master: https://github.com/FelixKratz/SketchyBar/commit/1648fa867ca166cacb6b068b255d56f52d85d69b if you want you can install from head to get this fix prior to the next release.

**Closed** 2023-01-08 13:26 UTC
Labels: available on master, unexpected behavior

**Comment by braun-steven** [comment] 2023-03-03 09:55
> I actually want to hide empty spaces or spaces that just have a specific set of programs open.

Do you have a script for that?
