### ISSUE TITLE
query show subscribed events

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#94] opened 2021-11-01 00:23 UTC
`sketchybar -m --query item <item>` should show the subscribed events that it has.

**Comment by FelixKratz** [comment] 2021-11-01 11:21
Duplicate of #55

**Closed by FelixKratz** 2021-11-01 11:21 UTC
Labels: duplicate

**Comment by FelixKratz** [comment] 2021-11-01 13:40
Events and their tag bit can now be queried via
```bash
sketchybar -m --query events
```
