### ISSUE TITLE
The Click Script shouldn't activate in Fullscreen applications

### ISSUE THREAD

**Issue by SleepySwords** [FelixKratz/SketchyBar#11] opened 2021-08-20 08:59 UTC
The click script shouldn't activate fullscreen applications as you are not able to see Sketchybar.

**Comment by FelixKratz** [comment] 2021-08-20 09:14
Yes, I want to work on this tonight, duplicate of #3

**Comment by SleepySwords** [comment] 2021-08-20 09:39
Ah alright, I'll close this then.

**Comment by FelixKratz** [comment] 2021-08-21 10:56
Should be fixed now bc006b5d41e0c6c569a6a6a39b1c91d8983a9ad7

**Comment by SleepySwords** [comment] 2021-08-21 13:27
Misclicked

**Closed** 2021-08-21 13:26 UTC
