### ISSUE TITLE
Mouse click event not captured on unfocused displays

### ISSUE THREAD

**Issue by LibofRelax** [FelixKratz/SketchyBar#392] opened 2023-08-31 10:20 UTC
After upgrading to v2.16.2, clicking on an icon that's not on the current focused display won't produce a mouse click event. For example, I'm now typing in the browser on display 1; if I click a sketchbar icon on display 2, the callback script won't be called. I've tested with a script that prints a message when clicked and confirmed no event was received.

I'm using sketchybar with yabai v5.0.7. Is it possible that yabai's space focus logic interferes with sketchybar?

**Comment by FelixKratz** [comment] 2023-08-31 11:14
This is a side-effect of the new mouse/event system. The new API I am using seems to not report any mouse events on non-focussed displays.

I realize that this suboptimal but going back to the rust Carbon API would be even more suboptimal I think. Maybe I can improve on the current design by doing some more research.

**Comment by LibofRelax** [comment] 2023-09-01 02:04
Thank you! Maybe I can dig into this if I manage to find time.

**Comment by LibofRelax** [comment] 2023-09-22 07:34
v2.16.3 fixed this issue for me. Cheers.

**Comment by mrpmohiburrahman** [comment] 2023-09-27 06:54
Hi, @FelixKratz,

I have upgraded to mac os sonoma today, and faced with slightly similar issue.
In my case the clicking on the window numbers is not working even in the focused display.

Sketchybar: v 2.16.3
Yabai: 5.0.8


![screenshot](https://github.com/FelixKratz/SketchyBar/assets/35300157/9cd48cc7-050f-4180-827b-26210006c685)

**Comment by FelixKratz** [comment] 2023-09-27 12:01
It is a change in Sonoma that causes moise events to not work at all. I will soon prepare a patch for Sonoma, then the original issue will be solved as well.

**Comment by FelixKratz** [comment] 2023-09-30 12:03
All of these issues should be fixed in v.2.16.4

**Closed by FelixKratz** 2023-09-30 12:03 UTC
Labels: unexpected behavior

**Comment by johnallen3d** [comment] 2024-01-15 15:42
Hey @FelixKratz - I'm playing around with adding `popup` windows to my bar today and have found that I can't get clicks to trigger. In fact, I'm realizing that none of my, recent working, `click_script` are triggering. After reading this it hit me that I installed the latest Sanoma update (14.2.1) a couple of days ago. Could that be related?

**Comment by FelixKratz** [comment] 2024-01-15 16:03
I am on 14.2.1 as well an my click scripts seem to be working can you provide a minimal example which does not work for you?

**Comment by FelixKratz** [comment] 2024-01-15 16:55
We can try some other things to narrow down the problem some more:

* What does `sketchybar --query test` return?
* Do sliders work? E.g. can you slide the slider with the mouse?
```bash
sketchybar --add slider slider left 100 --set slider slider.background.color=0xffffffff slider.highlight_color=0xffff0000 slider.background.height=15
```
* Do regular mouse.clicked events work? E.g.:
```bash
sketchybar --add item test left --set test label="Click Me" script='osascript -e "display dialog \"Hallo\""' --subscribe test mouse.clicked
```

**Comment by johnallen3d** [comment] 2024-01-15 17:06
1. `query test`

```
❯ sketchybar --query test
{
	"name": "test",
	"type": "item",
	"geometry": {
		"drawing": "on",
		"position": "left",
		"associated_space_mask": 0,
		"associated_display_mask": 0,
		"ignore_association": "off",
		"y_offset": 0,
		"width": 0,
		"padding_left": 0,
		"padding_right": -1,
		"background": {
			"drawing": "off",
			"color": "0x0",
			"border_color": "0x0",
			"border_width": 0,
			"height": 0,
			"corner_radius": 0,
			"padding_left": 0,
			"padding_right": 0,
			"y_offset": 0,
			"clip": 0.000000,
			"image": {
				"value": "(null)",
				"drawing": "off",
				"scale": 1.000000
			},
			"shadow": {
				"drawing": "off",
				"color": "0xff000000",
				"angle": 30,
				"distance": 5
			}
		}
	},
	"icon": {
		"value": "",
		"drawing": "on",
		"highlight": "off",
		"color": "0xffffffff",
		"highlight_color": "0xff000000",
		"padding_left": 0,
		"padding_right": 0,
		"y_offset": 0,
		"font": "Hack Nerd Font:Bold:14.00",
		"width": 0,
		"align": "left",
		"background": {
			"drawing": "off",
			"color": "0x0",
			"border_color": "0x0",
			"border_width": 0,
			"height": 0,
			"corner_radius": 0,
			"padding_left": 0,
			"padding_right": 0,
			"y_offset": 0,
			"clip": 0.000000,
			"image": {
				"value": "(null)",
				"drawing": "off",
				"scale": 1.000000
			},
			"shadow": {
				"drawing": "off",
				"color": "0xff000000",
				"angle": 30,
				"distance": 5
			}
		},
		"shadow": {
			"drawing": "off",
			"color": "0xff000000",
			"angle": 30,
			"distance": 5
		}
	},
	"label": {
		"value": "Click Me",
		"drawing": "on",
		"highlight": "off",
		"color": "0xffffffff",
		"highlight_color": "0xff000000",
		"padding_left": 0,
		"padding_right": 0,
		"y_offset": 0,
		"font": "Hack Nerd Font:Bold:14.00",
		"width": 0,
		"align": "left",
		"background": {
			"drawing": "off",
			"color": "0x0",
			"border_color": "0x0",
			"border_width": 0,
			"height": 0,
			"corner_radius": 0,
			"padding_left": 0,
			"padding_right": 0,
			"y_offset": 0,
			"clip": 0.000000,
			"image": {
				"value": "(null)",
				"drawing": "off",
				"scale": 1.000000
			},
			"shadow": {
				"drawing": "off",
				"color": "0xff000000",
				"angle": 30,
				"distance": 5
			}
		},
		"shadow": {
			"drawing": "off",
			"color": "0xff000000",
			"angle": 30,
			"distance": 5
		}
	},
	"scripting": {
		"script": "(null)",
		"click_script": "osascript -e \"display dialog \\"Works\\"\"",
		"update_freq": 0,
		"update_mask": 0,
		"updates": "on"
	},
	"bounding_rects": {
		"display-1": {
			"origin": [ 20.000000, 0.000000 ],
			"size": [ 68.000000, 25.000000 ]
		},
		"display-2": {
			"origin": [ 1372.000000, -349.000000 ],
			"size": [ 68.000000, 25.000000 ]
		}
	}
}
```

2. sliders - no
3. regular `mouse.clicked` - no
4. restart (`sketchybar` and macOS) - no

**Comment by FelixKratz** [comment] 2024-01-15 17:16
Ok, next steps for debugging are in code, are you able to build from source?

First interesting test would be:
put `printf("Mouse Event\n")` above this line:
https://github.com/FelixKratz/SketchyBar/blob/6ff8ffabef129fa823c9b38924ab39c71ea428be/src/mouse.c#L20

**Comment by johnallen3d** [comment] 2024-01-15 17:47
OK, thanks for sticking with my @FelixKratz. I do see "Mouse Event" but I _do not_ see "item: " when adding these debug lines.

**Comment by johnallen3d** [comment] 2024-01-15 18:07
OK, I don't know what I did wrong last time but I _am_ getting all the way through `event_mouse_up`. 🤦‍♂️

```bash
wid: 362
adid: 0
after bar_manager_refresh
```

I'm on Arm.

**Comment by FelixKratz** [comment] 2024-01-15 18:10
Yes, have a look inside `bar_item_on_click`. Does it survive the first check? I.e. is `bar_item` not `NULL`?

**Comment by johnallen3d** [comment] 2024-01-15 18:11
Nope, it dies here: https://github.com/FelixKratz/SketchyBar/blob/6ff8ffabef129fa823c9b38924ab39c71ea428be/src/bar_item.c#L205

**Comment by johnallen3d** [comment] 2024-01-15 18:15
`bar_item` appears to be `0`

**Comment by FelixKratz** [comment] 2024-01-15 18:17
Ok, then back to the `event_mouse_up` function. The `bar_item` variable is neither populated from its `wid` (via `bar_manager_get_item_by_wid(&g_bar_manager,
                                                          wid,
                                                          adid           );`) nor from the mouse click position (`bar_manager_get_item_by_point(&g_bar_manager, point, adid)`).

Question is why. Since `bar_manager_get_item_by_point(&g_bar_manager, point, adid)` is the fallback and should always detect the bar_item over which the mouse is over, we should investigate this function next.
* What are the parameters with which `bar_manager_get_item_by_point` is invoked?

**Comment by FelixKratz** [comment] 2024-01-15 18:18
Oh I overlooked something above that is probably already the problem.... `adid` should not be zero.

**Comment by johnallen3d** [comment] 2024-01-15 18:23
Was just grabbing all the values through `adid`:

```
point: 4653974661560795136
wid: 514
type: 2
mouse_button_code: 0
modifier_keys: 0
adid: 0
```

Will checkout `display_arrangement` now.

**Comment by johnallen3d** [comment] 2024-01-15 18:27
Looks like `display_uuid(did)` is returning `0`. So not making it through that function.

**Comment by FelixKratz** [comment] 2024-01-15 18:31
Can you check the value of `did`?

**Comment by johnallen3d** [comment] 2024-01-15 18:36
Ok, interesting, I just disconnected my external and the click worked as expected (eg. I saw the "Works" dialog). When I reconnect it does not work. 🤔

**Comment by FelixKratz** [comment] 2024-01-15 19:33
The function `display_uuid` failing is bad, several other things will probably not work as well, such as
```bash
sketchybar --set test display=active
```
should only render the test item (from above) only on the active display. Can you check if this is indeed the case?

**Comment by johnallen3d** [comment] 2024-01-15 20:08
I can also say that about a week ago, while converting my config to Lua, `click_script` was working just fine with an external monitor connected. The difference being, since then, the macOS update.

**Comment by FelixKratz** [comment] 2024-01-15 20:34
Can you try the latest commit?

**Comment by johnallen3d** [comment] 2024-01-15 20:55
Same behaviour, works w/o external, does not work w/ external. At a glance, `adid` is still `0` with the external connected.

**Comment by FelixKratz** [comment] 2024-01-15 21:11
I think I know why. It has to to with the option: "Displays have separate spaces" in System Settings under Desktop & Dock.
If you activate it it works. If it is deactivated I can reproduce the issue. Now I will be able to provide a fix.

**Comment by johnallen3d** [comment] 2024-01-15 22:35
OK, nice find! It's possible I changed this setting in that time span as well (sorry I forgot) when switching from Yabai to Aerospace [related docs](https://nikitabobko.github.io/AeroSpace/guide.html#a-note-on-displays-have-separate-spaces). I've had some odd issues with that setting enabled so I had switched it off.

**Comment by FelixKratz** [comment] 2024-01-15 22:49
I have included a check on startup. Just too many things are completely broken when the active display id is not reported properly. Maybe I find another way to get the id of the active display, then the bar should again work with this option turned off.
