### ISSUE TITLE
Very high cpu usage.

### ISSUE THREAD

**Issue by Princypal1** [FelixKratz/SketchyBar#343] opened 2023-03-17 15:30 UTC
Hi,

My cpu usage is through the roof and my Mac has slowed down a lot. I have confirmed sketchy bar is the issue as running "brew services stop sketchybar" stops the issue. Does anyone have a solution to this?

**Comment by FelixKratz** [comment] 2023-03-17 15:50
Duplicate of #342

**Closed as completed by FelixKratz** 2023-03-17 15:50 UTC
